AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ben-rms-bucekt-test/b5b1132e306ce1612b26b69019f9b6fd
      Runtime: nodejs8.10
      Handler: index.handler
      Environment:
        Variables:
          S3_BUCKET: ben-rms-bucekt-test
